name: Publish Develop Image

on:
  workflow_dispatch:

concurrency:
  group: docker-develop
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build-and-publish:
    needs: [ci]
    runs-on: ubuntu-latest

    steps:
      - name: Build project artifacts
        uses: ./.github/actions/build-sharkord

      - name: Build and publish Docker image
        uses: ./.github/actions/docker-build-publish
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ secrets.DOCKER_USERNAME }}/sharkord:develop
          labels: |
            org.opencontainers.image.title=Sharkord
            org.opencontainers.image.description=Sharkord Server (develop)
            org.opencontainers.image.source=https://github.com/Sharkord/sharkord
            org.opencontainers.image.revision=${{ github.sha }}
